// Generated from: ../../features/ai_features.feature
import { test } from "../../fixtures/index.ts";

test.describe('AI Features', () => {

  test.beforeEach('Background', async ({ Given, appServer, testData }, testInfo) => { if (testInfo.error) return;
    await Given('I create "1" tests with params:', {"docString":{"content":"{\n  \"testName\": \"AI Test - 1\",\n  \"checks\": [\n    {\n      \"checkName\": \"AI Check\",\n      \"filePath\": \"files/A.png\"\n    }\n  ]\n}"}}, { appServer, testData }); 
  });
  
  test('List checks via AI endpoint', { tag: ['@fast-server'] }, async ({ When, Then, And, appServer, request, testData }) => { 
    await When('I request "/ai/checks" with API key', null, { appServer, request, testData }); 
    await Then('I should receive an HTML response', null, { testData }); 
    await And('the response should contain "AI Check"', null, { testData }); 
    await And('the response should contain "Checks List"', null, { testData }); 
  });

  test('Get check details via AI endpoint', { tag: ['@fast-server'] }, async ({ When, Then, And, appServer, request, testData }) => { 
    await When('I request details for "AI Check" via AI endpoint', null, { appServer, request, testData }); 
    await Then('I should receive an HTML response', null, { testData }); 
    await And('the response should contain "AI Check"', null, { testData }); 
    await And('the response should contain "Metadata"', null, { testData }); 
  });

  test('Get analysis JSON', { tag: ['@fast-server'] }, async ({ When, Then, And, appServer, request, testData }) => { 
    await When('I request analysis for "AI Check" via AI endpoint', null, { appServer, request, testData }); 
    await Then('I should receive a JSON response', null, { testData }); 
    await And('the response should contain "images"', null, { testData }); 
    await And('the response should contain "context"', null, { testData }); 
  });

  test('Batch accept checks', { tag: ['@fast-server'] }, async ({ When, Then, And, appServer, request, testData }) => { 
    await When('I batch accept "AI Check" via AI endpoint', null, { appServer, request, testData }); 
    await Then('the check "AI Check" should be "new"', null, { appServer, request, testData }); 
    await And('the check "AI Check" should be marked as "accepted"', null, { appServer, request, testData }); 
  });

  test('Filter checks via AI endpoint', { tag: ['@fast-server'] }, async ({ When, Then, And, appServer, request, testData }) => { 
    await When('I filter checks by name "AI Check"', null, { appServer, request, testData }); 
    await Then('I should receive an HTML response', null, { testData }); 
    await And('the response should contain "AI Check"', null, { testData }); 
  });

  test('Filter checks by date range', { tag: ['@fast-server'] }, async ({ When, Then, And, appServer, request, testData }) => { 
    await When('I filter checks by date range', null, { appServer, request, testData }); 
    await Then('I should receive an HTML response', null, { testData }); 
    await And('the response should contain "AI Check"', null, { testData }); 
  });

  test('Get AI index page', { tag: ['@fast-server'] }, async ({ When, Then, And, appServer, request, testData }) => { 
    await When('I request "/ai/" with API key', null, { appServer, request, testData }); 
    await Then('I should receive an HTML response', null, { testData }); 
    await And('the response should contain "AI Endpoints Documentation"', null, { testData }); 
    await And('the response should contain "Common Use Cases"', null, { testData }); 
    await And('the response should not contain "< "', null, { testData }); 
  });

  test('Validate checks list HTML rendering', { tag: ['@fast-server'] }, async ({ When, Then, And, appServer, request, testData }) => { 
    await When('I request "/ai/checks" with API key', null, { appServer, request, testData }); 
    await Then('I should receive an HTML response', null, { testData }); 
    await And('the response should contain "Checks List"', null, { testData }); 
    await And('the response should not contain "< article"', null, { testData }); 
    await And('the response should not contain "< form"', null, { testData }); 
  });

  test('Validate check details HTML rendering', { tag: ['@fast-server'] }, async ({ When, Then, And, appServer, request, testData }) => { 
    await When('I request details for "AI Check" via AI endpoint', null, { appServer, request, testData }); 
    await Then('I should receive an HTML response', null, { testData }); 
    await And('the response should contain "AI Check"', null, { testData }); 
    await And('the response should contain "Metadata"', null, { testData }); 
    await And('the response should not contain "< article"', null, { testData }); 
    await And('the response should not contain "< figure"', null, { testData }); 
  });

  test('Export checks as JSON', { tag: ['@fast-server'] }, async ({ When, Then, And, appServer, request, testData }) => { 
    await When('I request "/ai/checks?format=json" with API key', null, { appServer, request, testData }); 
    await Then('I should receive a JSON response', null, { testData }); 
    await And('the JSON response should have property "results"', null, { testData }); 
    await And('the JSON response should have property "totalPages"', null, { testData }); 
  });

  test('Export checks as CSV', { tag: ['@fast-server'] }, async ({ When, Then, appServer, request, testData }) => { 
    await When('I request "/ai/checks?format=csv" with API key', null, { appServer, request, testData }); 
    await Then('I should receive a CSV response', null, { testData }); 
  });

  test('Filter by last seconds', { tag: ['@fast-server'] }, async ({ When, Then, appServer, request, testData }) => { 
    await When('I request "/ai/checks?lastSeconds=3600" with API key', null, { appServer, request, testData }); 
    await Then('I should receive an HTML response', null, { testData }); 
  });

  test('Field filtering with JSON export', { tag: ['@fast-server'] }, async ({ When, Then, And, appServer, request, testData }) => { 
    await When('I request "/ai/checks?fields=_id,name,status&format=json" with API key', null, { appServer, request, testData }); 
    await Then('I should receive a JSON response', null, { testData }); 
    await And('the JSON results should only contain specified fields', null, { testData }); 
  });

  test('Pagination with custom limit', { tag: ['@fast-server'] }, async ({ When, Then, And, appServer, request, testData }) => { 
    await When('I request "/ai/checks?limit=50" with API key', null, { appServer, request, testData }); 
    await Then('I should receive an HTML response', null, { testData }); 
    await And('the response should contain "Showing"', null, { testData }); 
  });

});

// == technical section ==

test.use({
  $test: [({}, use) => use(test), { scope: 'test', box: true }],
  $uri: [({}, use) => use('../../features/ai_features.feature'), { scope: 'test', box: true }],
  $bddFileData: [({}, use) => use(bddFileData), { scope: "test", box: true }],
});

const bddFileData = [ // bdd-data-start
  {"pwTestLine":10,"pickleLine":21,"tags":["@fast-server"],"steps":[{"pwStepLine":7,"gherkinStepLine":8,"keywordType":"Context","textWithKeyword":"Given I create \"1\" tests with params:","isBg":true,"stepMatchArguments":[{"group":{"start":9,"value":"\"1\"","children":[{"start":10,"value":"1","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]},{"pwStepLine":11,"gherkinStepLine":22,"keywordType":"Action","textWithKeyword":"When I request \"/ai/checks\" with API key","stepMatchArguments":[{"group":{"start":10,"value":"\"/ai/checks\"","children":[{"start":11,"value":"/ai/checks","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]},{"pwStepLine":12,"gherkinStepLine":23,"keywordType":"Outcome","textWithKeyword":"Then I should receive an HTML response","stepMatchArguments":[]},{"pwStepLine":13,"gherkinStepLine":24,"keywordType":"Outcome","textWithKeyword":"And the response should contain \"AI Check\"","stepMatchArguments":[{"group":{"start":28,"value":"\"AI Check\"","children":[{"start":29,"value":"AI Check","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]},{"pwStepLine":14,"gherkinStepLine":25,"keywordType":"Outcome","textWithKeyword":"And the response should contain \"Checks List\"","stepMatchArguments":[{"group":{"start":28,"value":"\"Checks List\"","children":[{"start":29,"value":"Checks List","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]}]},
  {"pwTestLine":17,"pickleLine":27,"tags":["@fast-server"],"steps":[{"pwStepLine":7,"gherkinStepLine":8,"keywordType":"Context","textWithKeyword":"Given I create \"1\" tests with params:","isBg":true,"stepMatchArguments":[{"group":{"start":9,"value":"\"1\"","children":[{"start":10,"value":"1","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]},{"pwStepLine":18,"gherkinStepLine":28,"keywordType":"Action","textWithKeyword":"When I request details for \"AI Check\" via AI endpoint","stepMatchArguments":[{"group":{"start":22,"value":"\"AI Check\"","children":[{"start":23,"value":"AI Check","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]},{"pwStepLine":19,"gherkinStepLine":29,"keywordType":"Outcome","textWithKeyword":"Then I should receive an HTML response","stepMatchArguments":[]},{"pwStepLine":20,"gherkinStepLine":30,"keywordType":"Outcome","textWithKeyword":"And the response should contain \"AI Check\"","stepMatchArguments":[{"group":{"start":28,"value":"\"AI Check\"","children":[{"start":29,"value":"AI Check","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]},{"pwStepLine":21,"gherkinStepLine":31,"keywordType":"Outcome","textWithKeyword":"And the response should contain \"Metadata\"","stepMatchArguments":[{"group":{"start":28,"value":"\"Metadata\"","children":[{"start":29,"value":"Metadata","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]}]},
  {"pwTestLine":24,"pickleLine":33,"tags":["@fast-server"],"steps":[{"pwStepLine":7,"gherkinStepLine":8,"keywordType":"Context","textWithKeyword":"Given I create \"1\" tests with params:","isBg":true,"stepMatchArguments":[{"group":{"start":9,"value":"\"1\"","children":[{"start":10,"value":"1","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]},{"pwStepLine":25,"gherkinStepLine":34,"keywordType":"Action","textWithKeyword":"When I request analysis for \"AI Check\" via AI endpoint","stepMatchArguments":[{"group":{"start":23,"value":"\"AI Check\"","children":[{"start":24,"value":"AI Check","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]},{"pwStepLine":26,"gherkinStepLine":35,"keywordType":"Outcome","textWithKeyword":"Then I should receive a JSON response","stepMatchArguments":[]},{"pwStepLine":27,"gherkinStepLine":36,"keywordType":"Outcome","textWithKeyword":"And the response should contain \"images\"","stepMatchArguments":[{"group":{"start":28,"value":"\"images\"","children":[{"start":29,"value":"images","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]},{"pwStepLine":28,"gherkinStepLine":37,"keywordType":"Outcome","textWithKeyword":"And the response should contain \"context\"","stepMatchArguments":[{"group":{"start":28,"value":"\"context\"","children":[{"start":29,"value":"context","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]}]},
  {"pwTestLine":31,"pickleLine":39,"tags":["@fast-server"],"steps":[{"pwStepLine":7,"gherkinStepLine":8,"keywordType":"Context","textWithKeyword":"Given I create \"1\" tests with params:","isBg":true,"stepMatchArguments":[{"group":{"start":9,"value":"\"1\"","children":[{"start":10,"value":"1","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]},{"pwStepLine":32,"gherkinStepLine":40,"keywordType":"Action","textWithKeyword":"When I batch accept \"AI Check\" via AI endpoint","stepMatchArguments":[{"group":{"start":15,"value":"\"AI Check\"","children":[{"start":16,"value":"AI Check","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]},{"pwStepLine":33,"gherkinStepLine":41,"keywordType":"Outcome","textWithKeyword":"Then the check \"AI Check\" should be \"new\"","stepMatchArguments":[{"group":{"start":10,"value":"\"AI Check\"","children":[{"start":11,"value":"AI Check","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"},{"group":{"start":31,"value":"\"new\"","children":[{"start":32,"value":"new","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]},{"pwStepLine":34,"gherkinStepLine":42,"keywordType":"Outcome","textWithKeyword":"And the check \"AI Check\" should be marked as \"accepted\"","stepMatchArguments":[{"group":{"start":10,"value":"\"AI Check\"","children":[{"start":11,"value":"AI Check","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"},{"group":{"start":41,"value":"\"accepted\"","children":[{"start":42,"value":"accepted","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]}]},
  {"pwTestLine":37,"pickleLine":43,"tags":["@fast-server"],"steps":[{"pwStepLine":7,"gherkinStepLine":8,"keywordType":"Context","textWithKeyword":"Given I create \"1\" tests with params:","isBg":true,"stepMatchArguments":[{"group":{"start":9,"value":"\"1\"","children":[{"start":10,"value":"1","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]},{"pwStepLine":38,"gherkinStepLine":44,"keywordType":"Action","textWithKeyword":"When I filter checks by name \"AI Check\"","stepMatchArguments":[{"group":{"start":24,"value":"\"AI Check\"","children":[{"start":25,"value":"AI Check","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]},{"pwStepLine":39,"gherkinStepLine":45,"keywordType":"Outcome","textWithKeyword":"Then I should receive an HTML response","stepMatchArguments":[]},{"pwStepLine":40,"gherkinStepLine":46,"keywordType":"Outcome","textWithKeyword":"And the response should contain \"AI Check\"","stepMatchArguments":[{"group":{"start":28,"value":"\"AI Check\"","children":[{"start":29,"value":"AI Check","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]}]},
  {"pwTestLine":43,"pickleLine":48,"tags":["@fast-server"],"steps":[{"pwStepLine":7,"gherkinStepLine":8,"keywordType":"Context","textWithKeyword":"Given I create \"1\" tests with params:","isBg":true,"stepMatchArguments":[{"group":{"start":9,"value":"\"1\"","children":[{"start":10,"value":"1","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]},{"pwStepLine":44,"gherkinStepLine":49,"keywordType":"Action","textWithKeyword":"When I filter checks by date range","stepMatchArguments":[]},{"pwStepLine":45,"gherkinStepLine":50,"keywordType":"Outcome","textWithKeyword":"Then I should receive an HTML response","stepMatchArguments":[]},{"pwStepLine":46,"gherkinStepLine":51,"keywordType":"Outcome","textWithKeyword":"And the response should contain \"AI Check\"","stepMatchArguments":[{"group":{"start":28,"value":"\"AI Check\"","children":[{"start":29,"value":"AI Check","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]}]},
  {"pwTestLine":49,"pickleLine":53,"tags":["@fast-server"],"steps":[{"pwStepLine":7,"gherkinStepLine":8,"keywordType":"Context","textWithKeyword":"Given I create \"1\" tests with params:","isBg":true,"stepMatchArguments":[{"group":{"start":9,"value":"\"1\"","children":[{"start":10,"value":"1","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]},{"pwStepLine":50,"gherkinStepLine":54,"keywordType":"Action","textWithKeyword":"When I request \"/ai/\" with API key","stepMatchArguments":[{"group":{"start":10,"value":"\"/ai/\"","children":[{"start":11,"value":"/ai/","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]},{"pwStepLine":51,"gherkinStepLine":55,"keywordType":"Outcome","textWithKeyword":"Then I should receive an HTML response","stepMatchArguments":[]},{"pwStepLine":52,"gherkinStepLine":56,"keywordType":"Outcome","textWithKeyword":"And the response should contain \"AI Endpoints Documentation\"","stepMatchArguments":[{"group":{"start":28,"value":"\"AI Endpoints Documentation\"","children":[{"start":29,"value":"AI Endpoints Documentation","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]},{"pwStepLine":53,"gherkinStepLine":57,"keywordType":"Outcome","textWithKeyword":"And the response should contain \"Common Use Cases\"","stepMatchArguments":[{"group":{"start":28,"value":"\"Common Use Cases\"","children":[{"start":29,"value":"Common Use Cases","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]},{"pwStepLine":54,"gherkinStepLine":58,"keywordType":"Outcome","textWithKeyword":"And the response should not contain \"< \"","stepMatchArguments":[{"group":{"start":32,"value":"\"< \"","children":[{"start":33,"value":"< ","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]}]},
  {"pwTestLine":57,"pickleLine":60,"tags":["@fast-server"],"steps":[{"pwStepLine":7,"gherkinStepLine":8,"keywordType":"Context","textWithKeyword":"Given I create \"1\" tests with params:","isBg":true,"stepMatchArguments":[{"group":{"start":9,"value":"\"1\"","children":[{"start":10,"value":"1","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]},{"pwStepLine":58,"gherkinStepLine":61,"keywordType":"Action","textWithKeyword":"When I request \"/ai/checks\" with API key","stepMatchArguments":[{"group":{"start":10,"value":"\"/ai/checks\"","children":[{"start":11,"value":"/ai/checks","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]},{"pwStepLine":59,"gherkinStepLine":62,"keywordType":"Outcome","textWithKeyword":"Then I should receive an HTML response","stepMatchArguments":[]},{"pwStepLine":60,"gherkinStepLine":63,"keywordType":"Outcome","textWithKeyword":"And the response should contain \"Checks List\"","stepMatchArguments":[{"group":{"start":28,"value":"\"Checks List\"","children":[{"start":29,"value":"Checks List","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]},{"pwStepLine":61,"gherkinStepLine":64,"keywordType":"Outcome","textWithKeyword":"And the response should not contain \"< article\"","stepMatchArguments":[{"group":{"start":32,"value":"\"< article\"","children":[{"start":33,"value":"< article","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]},{"pwStepLine":62,"gherkinStepLine":65,"keywordType":"Outcome","textWithKeyword":"And the response should not contain \"< form\"","stepMatchArguments":[{"group":{"start":32,"value":"\"< form\"","children":[{"start":33,"value":"< form","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]}]},
  {"pwTestLine":65,"pickleLine":67,"tags":["@fast-server"],"steps":[{"pwStepLine":7,"gherkinStepLine":8,"keywordType":"Context","textWithKeyword":"Given I create \"1\" tests with params:","isBg":true,"stepMatchArguments":[{"group":{"start":9,"value":"\"1\"","children":[{"start":10,"value":"1","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]},{"pwStepLine":66,"gherkinStepLine":68,"keywordType":"Action","textWithKeyword":"When I request details for \"AI Check\" via AI endpoint","stepMatchArguments":[{"group":{"start":22,"value":"\"AI Check\"","children":[{"start":23,"value":"AI Check","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]},{"pwStepLine":67,"gherkinStepLine":69,"keywordType":"Outcome","textWithKeyword":"Then I should receive an HTML response","stepMatchArguments":[]},{"pwStepLine":68,"gherkinStepLine":70,"keywordType":"Outcome","textWithKeyword":"And the response should contain \"AI Check\"","stepMatchArguments":[{"group":{"start":28,"value":"\"AI Check\"","children":[{"start":29,"value":"AI Check","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]},{"pwStepLine":69,"gherkinStepLine":71,"keywordType":"Outcome","textWithKeyword":"And the response should contain \"Metadata\"","stepMatchArguments":[{"group":{"start":28,"value":"\"Metadata\"","children":[{"start":29,"value":"Metadata","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]},{"pwStepLine":70,"gherkinStepLine":72,"keywordType":"Outcome","textWithKeyword":"And the response should not contain \"< article\"","stepMatchArguments":[{"group":{"start":32,"value":"\"< article\"","children":[{"start":33,"value":"< article","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]},{"pwStepLine":71,"gherkinStepLine":73,"keywordType":"Outcome","textWithKeyword":"And the response should not contain \"< figure\"","stepMatchArguments":[{"group":{"start":32,"value":"\"< figure\"","children":[{"start":33,"value":"< figure","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]}]},
  {"pwTestLine":74,"pickleLine":75,"tags":["@fast-server"],"steps":[{"pwStepLine":7,"gherkinStepLine":8,"keywordType":"Context","textWithKeyword":"Given I create \"1\" tests with params:","isBg":true,"stepMatchArguments":[{"group":{"start":9,"value":"\"1\"","children":[{"start":10,"value":"1","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]},{"pwStepLine":75,"gherkinStepLine":76,"keywordType":"Action","textWithKeyword":"When I request \"/ai/checks?format=json\" with API key","stepMatchArguments":[{"group":{"start":10,"value":"\"/ai/checks?format=json\"","children":[{"start":11,"value":"/ai/checks?format=json","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]},{"pwStepLine":76,"gherkinStepLine":77,"keywordType":"Outcome","textWithKeyword":"Then I should receive a JSON response","stepMatchArguments":[]},{"pwStepLine":77,"gherkinStepLine":78,"keywordType":"Outcome","textWithKeyword":"And the JSON response should have property \"results\"","stepMatchArguments":[{"group":{"start":39,"value":"\"results\"","children":[{"start":40,"value":"results","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]},{"pwStepLine":78,"gherkinStepLine":79,"keywordType":"Outcome","textWithKeyword":"And the JSON response should have property \"totalPages\"","stepMatchArguments":[{"group":{"start":39,"value":"\"totalPages\"","children":[{"start":40,"value":"totalPages","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]}]},
  {"pwTestLine":81,"pickleLine":81,"tags":["@fast-server"],"steps":[{"pwStepLine":7,"gherkinStepLine":8,"keywordType":"Context","textWithKeyword":"Given I create \"1\" tests with params:","isBg":true,"stepMatchArguments":[{"group":{"start":9,"value":"\"1\"","children":[{"start":10,"value":"1","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]},{"pwStepLine":82,"gherkinStepLine":82,"keywordType":"Action","textWithKeyword":"When I request \"/ai/checks?format=csv\" with API key","stepMatchArguments":[{"group":{"start":10,"value":"\"/ai/checks?format=csv\"","children":[{"start":11,"value":"/ai/checks?format=csv","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]},{"pwStepLine":83,"gherkinStepLine":83,"keywordType":"Outcome","textWithKeyword":"Then I should receive a CSV response","stepMatchArguments":[]}]},
  {"pwTestLine":86,"pickleLine":85,"tags":["@fast-server"],"steps":[{"pwStepLine":7,"gherkinStepLine":8,"keywordType":"Context","textWithKeyword":"Given I create \"1\" tests with params:","isBg":true,"stepMatchArguments":[{"group":{"start":9,"value":"\"1\"","children":[{"start":10,"value":"1","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]},{"pwStepLine":87,"gherkinStepLine":86,"keywordType":"Action","textWithKeyword":"When I request \"/ai/checks?lastSeconds=3600\" with API key","stepMatchArguments":[{"group":{"start":10,"value":"\"/ai/checks?lastSeconds=3600\"","children":[{"start":11,"value":"/ai/checks?lastSeconds=3600","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]},{"pwStepLine":88,"gherkinStepLine":87,"keywordType":"Outcome","textWithKeyword":"Then I should receive an HTML response","stepMatchArguments":[]}]},
  {"pwTestLine":91,"pickleLine":89,"tags":["@fast-server"],"steps":[{"pwStepLine":7,"gherkinStepLine":8,"keywordType":"Context","textWithKeyword":"Given I create \"1\" tests with params:","isBg":true,"stepMatchArguments":[{"group":{"start":9,"value":"\"1\"","children":[{"start":10,"value":"1","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]},{"pwStepLine":92,"gherkinStepLine":90,"keywordType":"Action","textWithKeyword":"When I request \"/ai/checks?fields=_id,name,status&format=json\" with API key","stepMatchArguments":[{"group":{"start":10,"value":"\"/ai/checks?fields=_id,name,status&format=json\"","children":[{"start":11,"value":"/ai/checks?fields=_id,name,status&format=json","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]},{"pwStepLine":93,"gherkinStepLine":91,"keywordType":"Outcome","textWithKeyword":"Then I should receive a JSON response","stepMatchArguments":[]},{"pwStepLine":94,"gherkinStepLine":92,"keywordType":"Outcome","textWithKeyword":"And the JSON results should only contain specified fields","stepMatchArguments":[]}]},
  {"pwTestLine":97,"pickleLine":94,"tags":["@fast-server"],"steps":[{"pwStepLine":7,"gherkinStepLine":8,"keywordType":"Context","textWithKeyword":"Given I create \"1\" tests with params:","isBg":true,"stepMatchArguments":[{"group":{"start":9,"value":"\"1\"","children":[{"start":10,"value":"1","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]},{"pwStepLine":98,"gherkinStepLine":95,"keywordType":"Action","textWithKeyword":"When I request \"/ai/checks?limit=50\" with API key","stepMatchArguments":[{"group":{"start":10,"value":"\"/ai/checks?limit=50\"","children":[{"start":11,"value":"/ai/checks?limit=50","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]},{"pwStepLine":99,"gherkinStepLine":96,"keywordType":"Outcome","textWithKeyword":"Then I should receive an HTML response","stepMatchArguments":[]},{"pwStepLine":100,"gherkinStepLine":97,"keywordType":"Outcome","textWithKeyword":"And the response should contain \"Showing\"","stepMatchArguments":[{"group":{"start":28,"value":"\"Showing\"","children":[{"start":29,"value":"Showing","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]}]},
]; // bdd-data-end